### PR TITLE
Add note about Chrome log filtering

### PR DESCRIPTION
**Pull request by RichardBradley**
It took me a while to figure out why my `debug` logs weren't showing, perhaps this will help other users?

### CODE REVIEW

**Comment by kutuluk** [comment]
loglevel uses console.log instead of console.debug and does not require any additional settings.

**Comment by RichardBradley** [comment]
These settings were necessary for me to have logging sent from `loglevel.debug("...")` to appear in Chrome ver 67.0.3396.79 on Win 10

**Comment by pimterry** [comment]
@RichardBradley which version of loglevel are you using? Since 1.5.0 `loglevel.debug` should map directly to console.log. If you're using that or later, and debug messages don't show up by default, that sounds like a bug.

**Comment by RichardBradley** [comment]
I'm on "1.4.1", yes, sorry. I'll update.

**Comment by pimterry** [comment]
Sure, no worries! Glad you got it sorted 👍

**Pull request closed without merging**
